pipeline {
    agent any

    stages {
        stage('Build') {
            agent {
                docker {
                    image 'alpine'
                }
            }
            steps {
                sh 'docker volume create alpine-django'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}
